<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="entregas_facturadosV2-20241024113322" tests="2" file=".py" time="70.442" timestamp="2024-10-24T11:34:33" failures="0" errors="2" skipped="0">
	<testcase classname="entregas_facturadosV2" name="test_delivery_applied" time="0.000" timestamp="0001-01-01T00:00:00" file="EntregasFactV2.py" line="23">
		<error type="AttributeError" message="'NoneType' object has no attribute 'text'"><![CDATA[Traceback (most recent call last):
  File "c:\Users\luist\repos\Automatizaciones_M-dulos-\EntregasFactV2.py", line 95, in test_delivery_applied
    validate_character_numeric_element(self.driver, tn_bruto)
  File "c:\Users\luist\repos\Automatizaciones_M-dulos-\Elements.py", line 1160, in validate_character_numeric_element
    valor = elemento.text
AttributeError: 'NoneType' object has no attribute 'text'
]]></error>
		<system-out><![CDATA[El texto encontrado es  MIS ENTREGAS
]]></system-out>
	</testcase>
	<testcase classname="entregas_facturadosV2" name="test_delivery_applied" time="70.442" timestamp="2024-10-24T11:34:33" file="EntregasFactV2.py" line="23">
		<error type="NoSuchWindowException" message="Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=130.0.6723.59)
Stacktrace:
	GetHandleVerifier [0x00007FF61AC73AB5+28005]
	(No symbol) [0x00007FF61ABD83B0]
	(No symbol) [0x00007FF61AA7580A]
	(No symbol) [0x00007FF61AA4FA85]
	(No symbol) [0x00007FF61AAF2AD7]
	(No symbol) [0x00007FF61AAF9D48]
	(No symbol) [0x00007FF61AAEBA00]
	(No symbol) [0x00007FF61AAB75C8]
	(No symbol) [0x00007FF61AAB8731]
	GetHandleVerifier [0x00007FF61AF6643D+3118829]
	GetHandleVerifier [0x00007FF61AFB6C90+3448640]
	GetHandleVerifier [0x00007FF61AFACF0D+3408317]
	GetHandleVerifier [0x00007FF61AD3A40B+841403]
	(No symbol) [0x00007FF61ABE340F]
	(No symbol) [0x00007FF61ABDF484]
	(No symbol) [0x00007FF61ABDF61D]
	(No symbol) [0x00007FF61ABCEB79]
	BaseThreadInitThunk [0x00007FF8AAC1257D+29]
	RtlUserThreadStart [0x00007FF8ABB0AF08+40]
"><![CDATA[Traceback (most recent call last):
  File "c:\Users\luist\repos\Automatizaciones_M-dulos-\EntregasFactV2.py", line 211, in tearDown
    self.driver.close()
  File "C:\Users\luist\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 465, in close
    self.execute(Command.CLOSE)
  File "C:\Users\luist\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 354, in execute
    self.error_handler.check_response(response)
  File "C:\Users\luist\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=130.0.6723.59)
Stacktrace:
	GetHandleVerifier [0x00007FF61AC73AB5+28005]
	(No symbol) [0x00007FF61ABD83B0]
	(No symbol) [0x00007FF61AA7580A]
	(No symbol) [0x00007FF61AA4FA85]
	(No symbol) [0x00007FF61AAF2AD7]
	(No symbol) [0x00007FF61AAF9D48]
	(No symbol) [0x00007FF61AAEBA00]
	(No symbol) [0x00007FF61AAB75C8]
	(No symbol) [0x00007FF61AAB8731]
	GetHandleVerifier [0x00007FF61AF6643D+3118829]
	GetHandleVerifier [0x00007FF61AFB6C90+3448640]
	GetHandleVerifier [0x00007FF61AFACF0D+3408317]
	GetHandleVerifier [0x00007FF61AD3A40B+841403]
	(No symbol) [0x00007FF61ABE340F]
	(No symbol) [0x00007FF61ABDF484]
	(No symbol) [0x00007FF61ABDF61D]
	(No symbol) [0x00007FF61ABCEB79]
	BaseThreadInitThunk [0x00007FF8AAC1257D+29]
	RtlUserThreadStart [0x00007FF8ABB0AF08+40]

]]></error>
		<system-out><![CDATA[El texto encontrado es  MIS ENTREGAS
]]></system-out>
	</testcase>
</testsuite>
