<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="detalle_ctro_fijacionesV2-20241106122845" tests="1" file=".py" time="82.216" timestamp="2024-11-06T12:30:08" failures="0" errors="1" skipped="0">
	<testcase classname="detalle_ctro_fijacionesV2" name="test_detail_fixings" time="82.216" timestamp="2024-11-06T12:30:08" file="CtaCtoDtaFijaV2.py" line="22">
		<error type="NoSuchWindowException" message="Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=130.0.6723.116)
Stacktrace:
	GetHandleVerifier [0x00007FF75B123B05+28005]
	(No symbol) [0x00007FF75B088400]
	(No symbol) [0x00007FF75AF2580A]
	(No symbol) [0x00007FF75AEFFA85]
	(No symbol) [0x00007FF75AFA2AD7]
	(No symbol) [0x00007FF75AFBB1B1]
	(No symbol) [0x00007FF75AF9B7E3]
	(No symbol) [0x00007FF75AF675C8]
	(No symbol) [0x00007FF75AF68731]
	GetHandleVerifier [0x00007FF75B41647D+3118813]
	GetHandleVerifier [0x00007FF75B466CD0+3448624]
	GetHandleVerifier [0x00007FF75B45CF4D+3408301]
	GetHandleVerifier [0x00007FF75B1EA45B+841403]
	(No symbol) [0x00007FF75B09345F]
	(No symbol) [0x00007FF75B08F4D4]
	(No symbol) [0x00007FF75B08F66D]
	(No symbol) [0x00007FF75B07EBC9]
	BaseThreadInitThunk [0x00007FFF3E62257D+29]
	RtlUserThreadStart [0x00007FFF4022AF08+40]
"><![CDATA[Traceback (most recent call last):
  File "c:\Users\luist\repos\Automatizaciones_M-dulos-\CtaCtoDtaFijaV2.py", line 24, in test_detail_fixings
    self.login_helper.login("admingd@silohub.ag", "G@viglio123")
  File "c:\Users\luist\repos\Automatizaciones_M-dulos-\loginhelper.py", line 9, in login
    user = find_element_by_id(self.driver, "email")  # asegÃºrate de pasar self.driver
  File "c:\Users\luist\repos\Automatizaciones_M-dulos-\findElements.py", line 10, in find_element_by_id
    return WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.ID, id)))
  File "C:\Users\luist\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\support\wait.py", line 96, in until
    value = method(self._driver)
  File "C:\Users\luist\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\support\expected_conditions.py", line 84, in _predicate
    return driver.find_element(*locator)
  File "C:\Users\luist\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 748, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Users\luist\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 354, in execute
    self.error_handler.check_response(response)
  File "C:\Users\luist\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=130.0.6723.116)
Stacktrace:
	GetHandleVerifier [0x00007FF75B123B05+28005]
	(No symbol) [0x00007FF75B088400]
	(No symbol) [0x00007FF75AF2580A]
	(No symbol) [0x00007FF75AEFFA85]
	(No symbol) [0x00007FF75AFA2AD7]
	(No symbol) [0x00007FF75AFBB1B1]
	(No symbol) [0x00007FF75AF9B7E3]
	(No symbol) [0x00007FF75AF675C8]
	(No symbol) [0x00007FF75AF68731]
	GetHandleVerifier [0x00007FF75B41647D+3118813]
	GetHandleVerifier [0x00007FF75B466CD0+3448624]
	GetHandleVerifier [0x00007FF75B45CF4D+3408301]
	GetHandleVerifier [0x00007FF75B1EA45B+841403]
	(No symbol) [0x00007FF75B09345F]
	(No symbol) [0x00007FF75B08F4D4]
	(No symbol) [0x00007FF75B08F66D]
	(No symbol) [0x00007FF75B07EBC9]
	BaseThreadInitThunk [0x00007FFF3E62257D+29]
	RtlUserThreadStart [0x00007FFF4022AF08+40]

]]></error>
	</testcase>
</testsuite>
