<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="CtaCtoDtalCertificados.detalle_cto_certificados-failed" tests="1" file="CtaCtoDtalCertificados.py" time="143.822" timestamp="2024-10-17T16:28:14" failures="0" errors="1" skipped="0">
	<testcase classname="CtaCtoDtalCertificados.detalle_cto_certificados" name="test_detail_certificates" time="143.822" timestamp="2024-10-17T16:28:14" file="CtaCtoDtalCertificados.py" line="22">
		<error type="AttributeError" message="'NoneType' object has no attribute 'is_displayed'"><![CDATA[Traceback (most recent call last):
  File "c:\Users\luist\repos\Automatizaciones_M-dulos-\CtaCtoDtalCertificados.py", line 109, in test_detail_certificates
    validate_text_visible(self.driver, element1, number_expected)
  File "c:\Users\luist\repos\Automatizaciones_M-dulos-\Elements.py", line 1178, in validate_text_visible
    is_visible = element.is_displayed()
AttributeError: 'NoneType' object has no attribute 'is_displayed'
]]></error>
		<system-out><![CDATA[¡Elemento encontrado y clickeado 3 veces con éxito!
¡Elemento encontrado y clickeado 8 veces con éxito!
¡Elemento encontrado y clickeado 3 veces con éxito!
Tiempo de espera agotado. El texto por texto no está presente.
Tiempo de espera agotado. El elemento no está presente o no es clickeable.
]]></system-out>
	</testcase>
</testsuite>
