<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Perfil_Usuario-20240320165202" tests="1" file=".py" time="25.355" timestamp="2024-03-20T16:52:27" failures="0" errors="1" skipped="0">
	<testcase classname="Perfil_Usuario" name="test_Profile_User" time="25.355" timestamp="2024-03-20T16:52:27" file="Profile_User.py" line="21">
		<error type="AttributeError" message="'WebDriver' object has no attribute 'find_element_by_id'"><![CDATA[Traceback (most recent call last):
  File "c:\Users\luist\repos\Automatizaciones-SILOHUB-\Profile_User.py", line 82, in test_Profile_User
    send_display_element_xpaht(self.driver,  insert_nationality, send_nationality )
  File "c:\Users\luist\repos\Automatizaciones-SILOHUB-\Elements.py", line 217, in send_display_element_xpaht
    input_element = driver.find_element_by_id(xpaht)
AttributeError: 'WebDriver' object has no attribute 'find_element_by_id'
]]></error>
		<system-out><![CDATA[¡Elemento encontrado y clickeado con éxito!
¡Elemento encontrado y clickeado con éxito!
El texto encontrado es  MIS DATOS
El texto encontrado es  Datos personales
¡Input encontrado y enviado con éxito!
¡Input encontrado y enviado con éxito!
La opcion fue seleccionada en el dropdown con exito  
¡Elemento encontrado y clickeado con éxito!
¡Elemento encontrado y clickeado con éxito!
]]></system-out>
	</testcase>
</testsuite>
