<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="contrato_operSecundarias-20240304153540" tests="1" file=".py" time="59.476" timestamp="2024-03-04T15:36:39" failures="1" errors="0" skipped="0">
	<testcase classname="contrato_operSecundarias" name="test_contratc_oparSecondary" time="59.476" timestamp="2024-03-04T15:36:39" file="CtaContOperSecundaria.py" line="22">
		<failure type="AssertionError" message=""><![CDATA[Traceback (most recent call last):
  File "c:\Users\luist\repos\Automatizaciones-SILOHUB-\CtaContOperSecundaria.py", line 101, in test_contratc_oparSecondary
    validate_text_visible(self.driver, element1, number_expected)
  File "c:\Users\luist\repos\Automatizaciones-SILOHUB-\Elements.py", line 979, in validate_text_visible
    assert text_obtained == text_expected
AssertionError
]]></failure>
		<system-out><![CDATA[¡Elemento encontrado y clickeado con éxito!
¡Elemento encontrado y clickeado con éxito!
¡Elemento encontrado y clickeado con éxito!
¡Elemento encontrado y clickeado con éxito!
¡Elemento encontrado y clickeado con éxito!
¡Elemento encontrado y clickeado con éxito!
¡Elemento encontrado y clickeado con éxito!
Tiempo de espera agotado. El elemento no está presente o no es clickeable.
¡Elemento encontrado y clickeado 3 veces con éxito!
¡Elemento encontrado y clickeado con éxito!
¡Elemento encontrado y clickeado con éxito!
¡Elemento encontrado y clickeado con éxito!
El texto encontrado es  Estado De Mis Contratos
¡Elemento encontrado y clickeado con éxito!
El texto es visible para el usuario
]]></system-out>
	</testcase>
</testsuite>
